### ISSUE TITLE
Toggle option

### ISSUE THREAD

**Issue by VRBat** [badhaloninja/Optizoom#1]
bool in NeosModSettings for **toggling zoom** rather than holding the button

**Comment by Hayden-Fluff** [comment]
I implemented this [on my fork](https://github.com/Hayden-Fluff/Optizoom) if you'd like to check that out.

**Comment by badhaloninja** [comment]
Resolved with [v1.2.0](https://github.com/badhaloninja/Optizoom/releases/tag/v1.2.0)
