### ISSUE TITLE
Optizoom brakes desktop emergency leave gesture

### ISSUE THREAD

**Issue by epicEaston197** [badhaloninja/Optizoom#6]
### Describe the bug?

Optizoom brakes desktop emergency leave gesture

### To Reproduce

1. Download Optizoom 
2. Hold down shift and double tap escape quickly
3. you will notice that the gesture does not make you leave from the current world you're in

### Expected behavior

holding down shift and double tapping escape should make me leave the current world I'm in as usual

### Resonite Version Number

Beta 2024.5.4.678

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-DAN95E7 - 2024.5.4.678 - 2024-05-05 09_49_21.log](https://github.com/badhaloninja/Optizoom/files/15213195/DESKTOP-DAN95E7.-.2024.5.4.678.-.2024-05-05.09_49_21.log)

### Reporters

@epicEaston197

**Comment by epicEaston197** [comment]
This might be because of a malformed config i don't know though
it's also not generating config files

**Comment by epicEaston197** [comment]
okay fix the config file to have proper enabled state but even when disabled I still can't do the emergency leave gesture

disabled
[DESKTOP-DAN95E7 - 2024.5.4.678 - 2024-05-05 10_23_12.log](https://github.com/badhaloninja/Optizoom/files/15213316/DESKTOP-DAN95E7.-.2024.5.4.678.-.2024-05-05.10_23_12.log)

enabled
[DESKTOP-DAN95E7 - 2024.5.4.678 - 2024-05-05 10_26_40.log](https://github.com/badhaloninja/Optizoom/files/15213319/DESKTOP-DAN95E7.-.2024.5.4.678.-.2024-05-05.10_26_40.log)

**Comment by XDelta** [comment]
I ran into this as the ctrl-tab world switching stopped working with only optizoom running.
Looks to cause `Userspace.OnCommonUpdate()` to not continue to run, so all the keybinds that are defined in there do not work.
such as the ones mentioned above, f3 debug and world switching.
```
6:13:14 AM.497 (  0 FPS)	Exception when Updating object: Element: ID9400, Type: FrooxEngine.Userspace, World: Userspace, IsRemoved: False, IsDestroyed: False, IsDisposed: False, Enabled: True
Element: ID8900, Type: FrooxEngine.Slot, World: Userspace, IsRemoved: False, Slot name: Userspace, T: [0; 0; 0], R: [0; 0; 0; 1], S: [1; 1; 1], ActiveSelf: True, IsDestroyed: False
Element: ID2400, Type: FrooxEngine.Slot, World: Userspace, IsRemoved: False, Slot name: Root, T: [0; 0; 0], R: [0; 0; 0; 1], S: [1; 1; 1], ActiveSelf: True, IsDestroyed: False
Element: ID0, Type: FrooxEngine.World, World: Userspace, IsRemoved: False


Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at Optizoom.Optizoom+SpyglassUserspacePatch.Update (FrooxEngine.Userspace __instance) [0x00098] in <767c6f8317f64f778e51e6535ee6d471>:0 
  at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.FrooxEngine.Userspace.OnCommonUpdate_Patch1(FrooxEngine.Userspace)
  at FrooxEngine.ComponentBase`1[C].InternalRunUpdate () [0x0001f] in <c3737839dc104e58a55be26c246bcfac>:0 
  at FrooxEngine.UpdateManager.RunUpdates () [0x0007c] in <c3737839dc104e58a55be26c246bcfac>:0 ```

**Comment by BlueCyro** [comment]
> I ran into this as the ctrl-tab world switching stopped working with only optizoom running. Looks to cause `Userspace.OnCommonUpdate()` to not continue to run, so all the keybinds that are defined in there do not work. such as the ones mentioned above, f3 debug and world switching.
> 
> ```
> 6:13:14 AM.497 (  0 FPS)	Exception when Updating object: Element: ID9400, Type: FrooxEngine.Userspace, World: Userspace, IsRemoved: False, IsDestroyed: False, IsDisposed: False, Enabled: True
> Element: ID8900, Type: FrooxEngine.Slot, World: Userspace, IsRemoved: False, Slot name: Userspace, T: [0; 0; 0], R: [0; 0; 0; 1], S: [1; 1; 1], ActiveSelf: True, IsDestroyed: False
> Element: ID2400, Type: FrooxEngine.Slot, World: Userspace, IsRemoved: False, Slot name: Root, T: [0; 0; 0], R: [0; 0; 0; 1], S: [1; 1; 1], ActiveSelf: True, IsDestroyed: False
> Element: ID0, Type: FrooxEngine.World, World: Userspace, IsRemoved: False
> 
> 
> Exception:
> System.NullReferenceException: Object reference not set to an instance of an object
>   at Optizoom.Optizoom+SpyglassUserspacePatch.Update (FrooxEngine.Userspace __instance) [0x00098] in <767c6f8317f64f778e51e6535ee6d471>:0 
>   at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.FrooxEngine.Userspace.OnCommonUpdate_Patch1(FrooxEngine.Userspace)
>   at FrooxEngine.ComponentBase`1[C].InternalRunUpdate () [0x0001f] in <c3737839dc104e58a55be26c246bcfac>:0 
>   at FrooxEngine.UpdateManager.RunUpdates () [0x0007c] in <c3737839dc104e58a55be26c246bcfac>:0 ```
> ```

Just as an FYI, the CTRL+Tab keybind breaking (without the exception) happens without any mods installed for me.

**Comment by XDelta** [comment]
Works fine here with no mods or with all but optizoom.

**Comment by badhaloninja** [comment]
> I ran into this as the ctrl-tab world switching stopped working with only optizoom running. Looks to cause `Userspace.OnCommonUpdate()` to not continue to run, so all the keybinds that are defined in there do not work. such as the ones mentioned above, f3 debug and world switching.
> 
> ```
> 6:13:14 AM.497 (  0 FPS)	Exception when Updating object: Element: ID9400, Type: FrooxEngine.Userspace, World: Userspace, IsRemoved: False, IsDestroyed: False, IsDisposed: False, Enabled: True
> Element: ID8900, Type: FrooxEngine.Slot, World: Userspace, IsRemoved: False, Slot name: Userspace, T: [0; 0; 0], R: [0; 0; 0; 1], S: [1; 1; 1], ActiveSelf: True, IsDestroyed: False
> Element: ID2400, Type: FrooxEngine.Slot, World: Userspace, IsRemoved: False, Slot name: Root, T: [0; 0; 0], R: [0; 0; 0; 1], S: [1; 1; 1], ActiveSelf: True, IsDestroyed: False
> Element: ID0, Type: FrooxEngine.World, World: Userspace, IsRemoved: False
> 
> 
> Exception:
> System.NullReferenceException: Object reference not set to an instance of an object
>   at Optizoom.Optizoom+SpyglassUserspacePatch.Update (FrooxEngine.Userspace __instance) [0x00098] in <767c6f8317f64f778e51e6535ee6d471>:0 
>   at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.FrooxEngine.Userspace.OnCommonUpdate_Patch1(FrooxEngine.Userspace)
>   at FrooxEngine.ComponentBase`1[C].InternalRunUpdate () [0x0001f] in <c3737839dc104e58a55be26c246bcfac>:0 
>   at FrooxEngine.UpdateManager.RunUpdates () [0x0007c] in <c3737839dc104e58a55be26c246bcfac>:0 ```
> ```

Interestingly I haven't been able to get optizoom to throw this error, though I was able to experience the world switch and close keybinds not working

Annoyingly it's hard to pinpoint what specifically causes the problem because rebuilding the mod seems to fix it for me 

@epicEaston197 could you try this version of the mod, it's just a rebuild against the latest resonite version
[Optizoom.zip](https://github.com/badhaloninja/Optizoom/files/15215391/Optizoom.zip)

**Comment by epicEaston197** [comment]
Yep my issue is fixed thanks!

**Comment by XDelta** [comment]
I'll also add that just swapping to the rebuilt dll appears to have fixed it for me as well.
